export const HOME = '/'
// export const SHOP = '/shop'
export const PRODUCTS = '/products'
export const PRODUCTS_SHOW = '/products/show'
export const CATEGORIES = '/categories'
export const PRODUCTS_CATEGORY = '/products/category'
export const CART = '/cart'
export const ITEM = '/item'
export const PRODUCT = '/product'
export const ABOUT = '/about'
// export const ACCOUNT = '/account'
// export const WISHLIST = '/account/wishlist'
// export const ORDERS = '/account/orders'
// export const SETTINGS = '/account/settings'
export const CREATE_ORDER = '/order'
export const CHECK = '/cart/check-availability'

export const BRAND = 'SAMPLE NAME'